### ISSUE TITLE
Migrate release automation to use Release Please for version management

### ISSUE THREAD

**Issue by Tiberriver256** [Tiberriver256/mcp-server-azure-devops#113]
## Background

Our release automation workflow (`.github/workflows/release.yml`) currently relies on `standard-version` for changelog generation and version bumping. While this approach works, it requires manual triggering of releases and doesn't fully automate the process based on commit standards.

After reviewing options, we've identified that Google's `release-please` library would be a better fit than Commitizen for our needs, especially since `standard-version` [recommends release-please](https://github.com/conventional-changelog/standard-version?tab=readme-ov-file#should-i-use-this-package) as a more automated approach.

## Current Approach

Our current workflow:
1. Requires manual triggering via `workflow_dispatch`
2. Uses `standard-version` to determine version bump based on commits
3. Extract changelog content and push changes/tags
4. Builds and publishes to npm
5. Creates a GitHub release

## Proposed Changes

We propose migrating to the `release-please` pattern which:
1. Fully automates version determination based on [Conventional Commits](https://www.conventionalcommits.org/)
2. Generates a standardized changelog
3. Creates GitHub releases with proper notes
4. Can trigger our npm publish workflow upon release

## Implementation Plan

1. **Add release-please workflow**: Create a new workflow file that handles version bumping and release PR creation
2. **Update dependencies**: Add required dependencies for release-please
3. **Modify existing workflow**: Adapt existing release workflow to be triggered by release-please releases

### Example release-please.yml workflow

```yaml
name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          # Using Node.js release type as we have a package.json
          release-type: node
          # This is a personal access token for creating GitHub releases
          token: ${{ secrets.RELEASE_PAT }}

      # The following steps only run if a new release is created
      - name: Checkout code
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.release.outputs.tag_name }}

      - name: Setup Node.js
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install Dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: npm ci

      - name: Build package
        if: ${{ steps.release.outputs.release_created }}
        run: npm run build

      - name: Publish to npm
        if: ${{ steps.release.outputs.release_created }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```

## Benefits

1. **Automation**: Eliminates manual release triggering - releases happen automatically based on commit history
2. **Standardization**: Enforces using [Conventional Commits](https://www.conventionalcommits.org/) which improves git history and changelog quality
3. **Clarity**: Provides clear visibility of pending changes through Release PRs 
4. **Reduced Manual Work**: Automates version bumping and changelog generation

## Next Steps

1. Review and approve this approach
2. Implement the `release-please.yml` workflow
3. Test with a minor/patch release
4. Update documentation to reflect new release process

## References

- [Release Please GitHub Action](https://github.com/googleapis/release-please-action)
- [Release Please Library](https://github.com/googleapis/release-please)
- [Conventional Commits](https://www.conventionalcommits.org/)
- [GitHub Release Action](https://github.com/softprops/action-gh-release)
